### ISSUE TITLE
Implement New Loader Styles in Extension UI

### ISSUE THREAD

**Issue by abhi9s-realm** [abhi9s-realm/snap-master#4]
Objective:
The current loader used in our extension has been functional but lacks the visual polish that aligns with our brand's aesthetics. We aim to introduce new loader styles to enhance user experience.

Background:
The existing loader is a simple spinning circle which is styled using basic CSS. While functional, it does not offer any form of alignment or enhanced user experience.

Requirements:
1. The new loader should be responsive and should not interfere with the functionality of the extension.
2. The loader should be styled in a manner consistent with the current theme of the extension, using CSS variables for easy theming.
3. The loader should be implemented without any additional dependencies.

**Comment by shba007** [comment]
Hi, Can I work on this?

**Comment by shba007** [comment]
Here are the two possible CSS Spinner I am thinking of

[Hexagon Spinner](https://codepen.io/osama-belal/pen/NZYrvM)
[CSS SVG Spinner](https://codepen.io/supah/pen/BjYLdW)

Let me know, what are you thinking of

**Comment by abhi9s-realm** [comment]
I've already added a spinner.
But this one looks cool though:  https://codepen.io/jkantner/pen/jOYejeq 
Implementing the ones with slower animation wouldn't help, as capturing the screenshot wont take much time.

**Comment by shba007** [comment]
We could do a screen flash like in android... It is quick

I got an idea which to show a tablet/laptop frame and the screen flash animation to capture the screenshot
![image](https://github.com/abhi9s-realm/snap-master/assets/48382105/703933d3-35f6-4e45-a558-70e442e050ef)

please let me know if you have interest in this idea then I will create a prototype on figma and share it with you

**Comment by abhi9s-realm** [comment]
@shba007  I've decided to move forward with the approach I initially suggested (i.e. https://codepen.io/jkantner/pen/jOYejeq) and have already started working on it.

**Comment by abhi9s-realm** [comment]
https://github.com/abhi9s-realm/snap-master/assets/3257989/3efeea50-3865-4086-a59e-0560a5c9496f
